In [1]:
#Pandas 0.22 and DataReader 0.5

In [2]:
import fix_yahoo_finance as yf

In [3]:
from pandas_datareader import data as pdr

import fix_yahoo_finance as yf
yf.pdr_override() # <== that's all it takes :-)

# download dataframe
data1 = pdr.get_data_yahoo("SPY", start="2017-01-01", end="2017-04-30")

# download Panel
data2 = pdr.get_data_yahoo(["SPY", "IWM"], start="2017-01-01", end="2017-04-30")

[*********************100%***********************]  1 of 1 downloaded
[*********************100%***********************]  2 of 2 downloaded

In [4]:
data1

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2017-01-03,225.039993,225.830002,223.880005,225.240005,218.092178,91366500
2017-01-04,225.619995,226.750000,225.610001,226.580002,219.389679,78744400
2017-01-05,226.270004,226.580002,225.479996,226.399994,219.215363,78379000
2017-01-06,226.529999,227.750000,225.899994,227.210007,219.999664,71559900
2017-01-09,226.910004,227.070007,226.419998,226.460007,219.273499,46265300
2017-01-10,226.479996,227.449997,226.009995,226.460007,219.273499,63771900
2017-01-11,226.360001,227.100006,225.589996,227.100006,219.893143,74650000
2017-01-12,226.500000,226.750000,224.960007,226.529999,219.341248,72113200
2017-01-13,226.729996,227.399994,226.690002,227.050003,219.844742,62717900
2017-01-17,226.309998,226.779999,225.800003,226.250000,219.070129,59261200
2017-01-18,226.539993,226.800003,225.899994,226.750000,219.554260,54793300
2017-01-19,226.839996,227.000000,225.410004,225.910004,218.740921,66608800
2017-01-20,226.699997,227.309998,225.970001,226.740005,219.544586,129168600
2017-01-23,226.740005,226.809998,225.270004,226.149994,218.973297,75061600
2017-01-24,226.399994,228.080002,226.270004,227.600006,220.377304,95555300
2017-01-25,228.699997,229.570007,228.509995,229.570007,222.284775,84437700
2017-01-26,229.399994,229.710007,229.009995,229.330002,222.052399,59970700
2017-01-27,229.419998,229.589996,228.759995,228.970001,221.703827,59711100
2017-01-30,228.169998,228.199997,226.410004,227.550003,220.328873,79737300
2017-01-31,226.979996,227.600006,226.320007,227.529999,220.309525,75880800
2017-02-01,227.529999,228.589996,226.940002,227.619995,220.396652,79117700
2017-02-02,227.619995,228.100006,226.820007,227.770004,220.541901,69657600
2017-02-03,228.820007,229.550003,228.460007,229.339996,222.062073,80563200
2017-02-06,228.869995,229.330002,228.539993,228.929993,221.665070,57790100
2017-02-07,229.380005,229.660004,228.720001,228.940002,221.674759,57931200
2017-02-08,228.940002,229.389999,228.309998,229.240005,221.965256,51566200
2017-02-09,229.240005,230.949997,229.240005,230.600006,223.282104,65955200
2017-02-10,231.000000,231.770004,230.619995,231.509995,224.163208,66015900
2017-02-13,232.080002,233.070007,232.050003,232.770004,225.383240,55182100
2017-02-14,232.559998,233.710007,232.160004,233.699997,226.283691,67794500
...,...,...,...,...,...,...
2017-03-17,237.750000,237.970001,237.029999,237.029999,230.506516,89002100
2017-03-20,237.029999,237.360001,236.320007,236.770004,230.253677,52537000
2017-03-21,237.470001,237.610001,233.580002,233.729996,227.297302,131809300
2017-03-22,233.770004,234.610001,233.050003,234.279999,227.832184,97569200
2017-03-23,234.279999,235.339996,233.600006,234.029999,227.589050,100410300
2017-03-24,234.380005,235.039993,232.960007,233.860001,227.423752,112504900
2017-03-27,231.929993,233.919998,231.610001,233.619995,227.190353,87454500
2017-03-28,233.270004,235.809998,233.139999,235.320007,228.843567,93483900
2017-03-29,234.990005,235.809998,234.729996,235.539993,229.057480,61950400
2017-03-30,235.470001,236.520004,235.270004,236.289993,229.786850,56737900
2017-03-31,235.899994,236.509995,235.679993,235.740005,229.251999,73733100
2017-04-03,235.800003,236.029999,233.910004,235.330002,228.853302,85546500
2017-04-04,235.000000,235.580002,234.559998,235.479996,228.999161,56466200
2017-04-05,236.259995,237.389999,234.539993,234.779999,228.318436,108800600
2017-04-06,234.940002,236.039993,234.429993,235.440002,228.960281,69135800
2017-04-07,235.149994,236.000000,234.639999,235.199997,228.726868,74412300
2017-04-10,235.360001,236.259995,234.729996,235.339996,228.863007,67615300
2017-04-11,234.899994,235.179993,233.339996,235.059998,228.590714,88045300
2017-04-12,234.740005,234.960007,233.770004,234.029999,227.589050,81864400
2017-04-13,233.639999,234.490005,232.509995,232.509995,226.110901,92880400
2017-04-17,233.110001,234.570007,232.880005,234.570007,228.114197,68405400
2017-04-18,233.720001,234.490005,233.080002,233.869995,227.433441,83225800
2017-04-19,234.520004,234.949997,233.179993,233.440002,227.015289,68699900
2017-04-20,234.149994,235.850006,233.779999,235.339996,228.863007,92572200
2017-04-21,235.250000,235.309998,234.130005,234.589996,228.133636,110389800
2017-04-24,237.179993,237.410004,234.559998,237.169998,230.642639,119209900
2017-04-25,237.910004,238.949997,237.809998,238.550003,231.984680,76698300
2017-04-26,238.509995,239.529999,238.350006,238.399994,231.838791,84702500
2017-04-27,238.770004,238.949997,237.979996,238.600006,232.033295,57410300
2017-04-28,238.899994,238.929993,237.929993,238.080002,231.527603,53247400

In [5]:
data2

                  Open                    High                     Low  \
                   IWM         SPY         IWM         SPY         IWM
Date
2017-01-03  136.490005  225.039993  136.830002  225.830002  134.500000
2017-01-04  136.050003  225.619995  137.960007  226.750000  136.009995
2017-01-05  137.490005  226.270004  137.759995  226.580002  135.509995
2017-01-06  136.410004  226.529999  136.710007  227.750000  135.679993
2017-01-09  135.539993  226.910004  135.720001  227.070007  134.500000
2017-01-10  135.000000  226.479996  136.380005  227.449997  134.759995
2017-01-11  136.229996  226.360001  136.789993  227.100006  135.419998
2017-01-12  136.160004  226.500000  136.220001  226.750000  133.589996
2017-01-13  135.649994  226.729996  136.970001  227.399994  135.649994
2017-01-17  135.600006  226.309998  135.690002  226.779999  134.130005
2017-01-18  134.759995  226.539993  134.940002  226.800003  133.949997
2017-01-19  135.139999  226.839996  135.440002  227.000000  133.169998
2017-01-20  133.750000  226.699997  134.880005  227.309998  133.750000
2017-01-23  134.029999  226.740005  134.679993  226.809998  133.119995
2017-01-24  134.339996  226.399994  136.279999  228.080002  134.220001
2017-01-25  137.059998  228.699997  137.550003  229.570007  136.949997
2017-01-26  137.339996  229.399994  137.500000  229.710007  136.419998
2017-01-27  136.770004  229.419998  137.039993  229.589996  135.649994
2017-01-30  135.229996  228.169998  135.240005  228.199997  133.240005
2017-01-31  133.869995  226.979996  135.559998  227.600006  133.479996
2017-02-01  136.220001  227.529999  136.869995  228.589996  134.699997
2017-02-02  135.300003  227.619995  135.669998  228.100006  134.490005
2017-02-03  135.990005  228.820007  136.979996  229.550003  135.509995
2017-02-06  136.399994  228.869995  136.779999  229.330002  135.429993
2017-02-07  135.820007  229.380005  136.470001  229.660004  134.770004
2017-02-08  135.240005  228.940002  135.240005  229.389999  133.889999
2017-02-09  135.000000  229.240005  137.250000  230.949997  135.000000
2017-02-10  137.789993  231.000000  138.369995  231.770004  137.199997
2017-02-13  138.770004  232.080002  139.210007  233.070007  138.089996
2017-02-14  137.940002  232.559998  138.949997  233.710007  137.610001
...                ...         ...         ...         ...         ...
2017-03-17  138.139999  237.750000  138.729996  237.970001  137.309998
2017-03-20  138.279999  237.029999  138.520004  237.360001  137.369995
2017-03-21  138.509995  237.470001  138.600006  237.610001  133.919998
2017-03-22  133.710007  233.770004  134.309998  234.610001  132.779999
2017-03-23  134.000000  234.279999  135.699997  235.339996  133.639999
2017-03-24  134.949997  234.380005  135.470001  235.039993  133.860001
2017-03-27  132.759995  231.929993  135.070007  233.919998  132.399994
2017-03-28  134.279999  233.270004  135.899994  235.809998  134.139999
2017-03-29  135.699997  234.990005  136.490005  235.809998  135.300003
2017-03-30  136.320007  235.470001  137.380005  236.520004  136.259995
2017-03-31  137.419998  235.899994  138.169998  236.509995  136.940002
2017-04-03  137.970001  235.800003  138.100006  236.029999  135.600006
2017-04-04  135.929993  235.000000  136.550003  235.580002  135.350006
2017-04-05  136.830002  236.259995  137.429993  237.389999  134.080002
2017-04-06  134.539993  234.940002  135.630005  236.039993  133.830002
2017-04-07  135.210007  235.149994  136.029999  236.000000  134.750000
2017-04-10  135.470001  235.360001  136.850006  236.259995  135.160004
2017-04-11  135.270004  234.899994  136.919998  235.179993  135.080002
2017-04-12  136.639999  234.740005  136.699997  234.960007  134.919998
2017-04-13  134.880005  233.639999  135.369995  234.490005  133.660004
2017-04-17  134.070007  233.110001  135.320007  234.570007  133.679993
2017-04-18  134.720001  233.720001  135.460007  234.490005  134.160004
2017-04-19  135.690002  234.520004  136.960007  234.949997  135.539993
2017-04-20  136.339996  234.149994  137.669998  235.850006  136.149994
2017-04-21  137.240005  235.250000  137.550003  235.309998  136.710007
2017-04-24  139.080002  237.179993  139.339996  237.410004  138.490005
2017-04-25  140.240005  237.910004  140.880005  238.949997  140.089996
2017-04-26  140.169998  238.509995  141.820007  239.529999  140.130005
2017-04-27  141.339996  238.770004  141.800003  238.949997  140.479996
2017-04-28  141.029999  238.899994  141.169998  238.929993  139.039993

                             Close               Adj Close              \
                   SPY         IWM         SPY         IWM         SPY
Date
2017-01-03  223.880005  135.520004  225.240005  132.576813  218.092178
2017-01-04  225.610001  137.779999  226.580002  134.787720  219.389679
2017-01-05  225.479996  136.190002  226.399994  133.232254  219.215363
2017-01-06  225.899994  135.690002  227.210007  132.743088  219.999664
2017-01-09  226.419998  134.800003  226.460007  131.872452  219.273499
2017-01-10  226.009995  136.089996  226.460007  133.134415  219.273499
2017-01-11  225.589996  136.330002  227.100006  133.369217  219.893143
2017-01-12  224.960007  135.279999  226.529999  132.342010  219.341248
2017-01-13  226.690002  136.259995  227.050003  133.300735  219.844742
2017-01-17  225.800003  134.410004  226.250000  131.490906  219.070129
2017-01-18  225.899994  134.850006  226.750000  131.921356  219.554260
2017-01-19  225.410004  133.750000  225.910004  130.845230  218.740921
2017-01-20  225.970001  134.440002  226.740005  131.520248  219.544586
2017-01-23  225.270004  133.880005  226.149994  130.972412  218.973297
2017-01-24  226.270004  135.929993  227.600006  132.977921  220.377304
2017-01-25  228.509995  137.210007  229.570007  134.230103  222.284775
2017-01-26  229.009995  136.660004  229.330002  133.692062  222.052399
2017-01-27  228.759995  136.190002  228.970001  133.232254  221.703827
2017-01-30  226.410004  134.289993  227.550003  131.373505  220.328873
2017-01-31  226.320007  135.229996  227.529999  132.293076  220.309525
2017-02-01  226.940002  135.149994  227.619995  132.214828  220.396652
2017-02-02  226.820007  134.809998  227.770004  131.882202  220.541901
2017-02-03  228.460007  136.869995  229.339996  133.897491  222.062073
2017-02-06  228.539993  135.839996  228.929993  132.889847  221.665070
2017-02-07  228.720001  135.240005  228.940002  132.302887  221.674759
2017-02-08  228.309998  135.000000  229.240005  132.068100  221.965256
2017-02-09  229.240005  136.899994  230.600006  133.926819  223.282104
2017-02-10  230.619995  137.940002  231.509995  134.944260  224.163208
2017-02-13  232.050003  138.300003  232.770004  135.296432  225.383240
2017-02-14  232.160004  138.759995  233.699997  135.746445  226.283691
...                ...         ...         ...         ...         ...
2017-03-17  237.029999  138.460007  237.029999  135.452972  230.506516
2017-03-20  236.320007  137.860001  236.770004  134.865997  230.253677
2017-03-21  233.580002  133.970001  233.729996  131.060471  227.297302
2017-03-22  233.050003  134.000000  234.279999  131.089798  227.832184
2017-03-23  233.600006  134.779999  234.029999  131.852859  227.589050
2017-03-24  232.960007  134.490005  233.860001  131.948013  227.423752
2017-03-27  231.610001  134.740005  233.619995  132.193314  227.190353
2017-03-28  233.139999  135.789993  235.320007  133.223480  228.843567
2017-03-29  234.729996  136.229996  235.539993  133.655136  229.057480
2017-03-30  235.270004  137.259995  236.289993  134.665680  229.786850
2017-03-31  235.679993  137.479996  235.740005  134.881531  229.251999
2017-04-03  233.910004  136.029999  235.330002  133.458923  228.853302
2017-04-04  234.559998  135.869995  235.479996  133.301941  228.999161
2017-04-05  234.539993  134.330002  234.779999  131.791046  228.318436
2017-04-06  234.429993  135.580002  235.440002  133.017441  228.960281
2017-04-07  234.639999  135.520004  235.199997  132.958588  228.726868
2017-04-10  234.729996  135.820007  235.339996  133.252930  228.863007
2017-04-11  233.339996  136.899994  235.059998  134.312485  228.590714
2017-04-12  233.770004  135.039993  234.029999  132.487640  227.589050
2017-04-13  232.509995  133.720001  232.509995  131.192596  226.110901
2017-04-17  232.880005  135.289993  234.570007  132.732910  228.114197
2017-04-18  233.080002  135.320007  233.869995  132.762329  227.433441
2017-04-19  233.179993  135.789993  233.440002  133.223480  227.015289
2017-04-20  233.779999  137.520004  235.339996  134.920792  228.863007
2017-04-21  234.130005  137.210007  234.589996  134.616638  228.133636
2017-04-24  234.559998  138.919998  237.169998  136.294312  230.642639
2017-04-25  237.809998  140.270004  238.550003  137.618774  231.984680
2017-04-26  238.350006  140.990005  238.399994  138.325180  231.838791
2017-04-27  237.979996  140.949997  238.600006  138.285919  232.033295
2017-04-28  237.929993  139.059998  238.080002  136.431671  231.527603

              Volume
                 IWM        SPY
Date
2017-01-03  29792400   91366500
2017-01-04  34499400   78744400
2017-01-05  30286900   78379000
2017-01-06  23436000   71559900
2017-01-09  22572800   46265300
2017-01-10  21684900   63771900
2017-01-11  27428800   74650000
2017-01-12  41844200   72113200
2017-01-13  27784500   62717900
2017-01-17  26626800   59261200
2017-01-18  21289700   54793300
2017-01-19  34105900   66608800
2017-01-20  29286100  129168600
2017-01-23  20537000   75061600
2017-01-24  34313800   95555300
2017-01-25  29127300   84437700
2017-01-26  22255600   59970700
2017-01-27  19467800   59711100
2017-01-30  40464400   79737300
2017-01-31  32945000   75880800
2017-02-01  30010500   79117700
2017-02-02  19935700   69657600
2017-02-03  24534100   80563200
2017-02-06  23691500   57790100
2017-02-07  30342200   57931200
2017-02-08  32956900   51566200
2017-02-09  28267600   65955200
2017-02-10  27287600   66015900
2017-02-13  23245100   55182100
2017-02-14  26348100   67794500
...              ...        ...
2017-03-17  33324600   89002100
2017-03-20  19091200   52537000
2017-03-21  61869000  131809300
2017-03-22  46332600   97569200
2017-03-23  37764600  100410300
2017-03-24  33514400  112504900
2017-03-27  35596700   87454500
2017-03-28  26891900   93483900
2017-03-29  22119500   61950400
2017-03-30  25792900   56737900
2017-03-31  29434300   73733100
2017-04-03  38834900   85546500
2017-04-04  25642600   56466200
2017-04-05  44968800  108800600
2017-04-06  41012100   69135800
2017-04-07  24300200   74412300
2017-04-10  22779900   67615300
2017-04-11  32589200   88045300
2017-04-12  25700800   81864400
2017-04-13  30207000   92880400
2017-04-17  18278800   68405400
2017-04-18  24553300   83225800
2017-04-19  34627600   68699900
2017-04-20  31934400   92572200
2017-04-21  29386000  110389800
2017-04-24  33836900  119209900
2017-04-25  32751700   76698300
2017-04-26  41669200   84702500
2017-04-27  23004300   57410300
2017-04-28  28206700   53247400

[81 rows x 12 columns]

In [6]:
from pandas_datareader import data as pdr

import fix_yahoo_finance as yf
yf.pdr_override() # <== that's all it takes :-)

# download dataframe
APPLE = pdr.get_data_yahoo("AAPL", start="2017-01-01", end="2017-04-30")

[*********************100%***********************]  1 of 1 downloaded

In [7]:
APPLE['Close']

Date
2017-01-03    116.150002
2017-01-04    116.019997
2017-01-05    116.610001
2017-01-06    117.910004
2017-01-09    118.989998
2017-01-10    119.110001
2017-01-11    119.750000
2017-01-12    119.250000
2017-01-13    119.040001
2017-01-17    120.000000
2017-01-18    119.989998
2017-01-19    119.779999
2017-01-20    120.000000
2017-01-23    120.080002
2017-01-24    119.970001
2017-01-25    121.879997
2017-01-26    121.940002
2017-01-27    121.949997
2017-01-30    121.629997
2017-01-31    121.349998
2017-02-01    128.750000
2017-02-02    128.529999
2017-02-03    129.080002
2017-02-06    130.289993
2017-02-07    131.529999
2017-02-08    132.039993
2017-02-09    132.419998
2017-02-10    132.119995
2017-02-13    133.289993
2017-02-14    135.020004
                 ...
2017-03-17    139.990005
2017-03-20    141.460007
2017-03-21    139.839996
2017-03-22    141.419998
2017-03-23    140.919998
2017-03-24    140.639999
2017-03-27    140.880005
2017-03-28    143.800003
2017-03-29    144.119995
2017-03-30    143.929993
2017-03-31    143.660004
2017-04-03    143.699997
2017-04-04    144.770004
2017-04-05    144.020004
2017-04-06    143.660004
2017-04-07    143.339996
2017-04-10    143.169998
2017-04-11    141.630005
2017-04-12    141.800003
2017-04-13    141.050003
2017-04-17    141.830002
2017-04-18    141.199997
2017-04-19    140.679993
2017-04-20    142.440002
2017-04-21    142.270004
2017-04-24    143.639999
2017-04-25    144.529999
2017-04-26    143.679993
2017-04-27    143.789993
2017-04-28    143.649994
Name: Close, Length: 81, dtype: float64

In [8]:
data = pdr.get_data_yahoo(
            # tickers list (single tickers accepts a string as well)
            tickers = ["SPY", "IWM", "..."],

            # start date (YYYY-MM-DD / datetime.datetime object)
            # (optional, defaults is 1950-01-01)
            start = "2017-01-01",

            # end date (YYYY-MM-DD / datetime.datetime object)
            # (optional, defaults is Today)
            end = "2017-04-30",

            # return a multi-index dataframe
            # (optional, default is Panel, which is deprecated)
            as_panel = False,

            # group by ticker (to access via data['SPY'])
            # (optional, default is 'column')
            group_by = 'ticker',

            # adjust all OHLC automatically
            # (optional, default is False)
            auto_adjust = True,

            # download dividend + stock splits data
            # (optional, default is None)
            # options are:
            #   - True (returns history + actions)
            #   - 'only' (actions only)
            actions = True,

            # How may threads to use?
            # threads = 10
        )

[*********************100%***********************]  3 of 3 downloaded

In [9]:
print(data)

                   SPY                                                 \
                  Open        High         Low       Close     Volume
Date
2017-01-03  217.898513  218.663452  216.775337  218.092178   91366500
2017-01-04  218.460137  219.554282  218.450460  219.389679   78744400
2017-01-05  219.089498  219.389659  218.324560  219.215363   78379000
2017-01-06  219.341236  220.522521  218.731223  219.999664   71559900
2017-01-09  219.709216  219.864141  219.234760  219.273499   46265300
2017-01-10  219.292854  220.232073  218.837768  219.273499   63771900
2017-01-11  219.176622  219.893143  218.431052  219.893143   74650000
2017-01-12  219.312201  219.554267  217.821078  219.341248   72113200
2017-01-13  219.534890  220.183626  219.496165  219.844742   62717900
2017-01-17  219.128223  219.583309  218.634412  219.070129   59261200
2017-01-18  219.350917  219.602676  218.731228  219.554260   54793300
2017-01-19  219.641400  219.796327  218.256788  218.740921   66608800
2017-01-20  219.505848  220.096491  218.799017  219.544586  129168600
2017-01-23  219.544584  219.612356  218.121233  218.973297   75061600
2017-01-24  219.215373  220.842068  219.089509  220.377304   95555300
2017-01-25  221.442374  222.284775  221.258402  222.284775   84437700
2017-01-26  222.120170  222.420345  221.742547  222.052399   59970700
2017-01-27  222.139544  222.304147  221.500485  221.703827   59711100
2017-01-30  220.929193  220.958240  219.225051  220.328873   79737300
2017-01-31  219.776976  220.377310  219.137931  220.309525   75880800
2017-02-01  220.309512  221.335871  219.738238  220.396652   79117700
2017-02-02  220.396652  220.861431  219.622051  220.541901   69657600
2017-02-03  221.558585  222.265416  221.210010  222.062073   80563200
2017-02-06  221.606976  222.052385  221.287446  221.665070   57790100
2017-02-07  222.100799  222.371912  221.461740  221.674759   57931200
2017-02-08  221.674773  222.110490  221.064762  221.965256   51566200
2017-02-09  221.965262  223.620988  221.965262  223.282104   65955200
2017-02-10  223.669397  224.414966  223.301451  224.163208   66015900
2017-02-13  224.715135  225.673723  224.686088  225.383240   55182100
2017-02-14  225.179869  226.293383  224.792569  226.283691   67794500
...                ...         ...         ...         ...        ...
2017-03-17  231.206701  231.420647  230.506516  230.506516   89002100
2017-03-20  230.506516  230.827436  229.816065  230.253677   52537000
2017-03-21  230.934375  231.070522  227.151436  227.297302  131809300
2017-03-22  227.336225  228.153104  226.636040  227.832184   97569200
2017-03-23  227.832170  228.862993  227.170891  227.589050  100410300
2017-03-24  227.929445  228.571268  226.548527  227.423752  112504900
2017-03-27  225.546863  227.482099  225.235678  227.190353   87454500
2017-03-28  226.849984  229.320073  226.723557  228.843567   93483900
2017-03-29  228.522629  229.320054  228.269776  229.057480   61950400
2017-03-30  228.989426  230.010531  228.794933  229.786850   56737900
2017-03-31  229.407585  230.000797  229.193639  229.251999   73733100
2017-04-03  229.310368  229.534034  227.472385  228.853302   85546500
2017-04-04  228.532375  229.096415  228.104483  228.999161   56466200
2017-04-05  229.757700  230.856604  228.085035  228.318436  108800600
2017-04-06  228.474042  229.543759  227.978069  228.960281   69135800
2017-04-07  228.678241  229.504853  228.182282  228.726868   74412300
2017-04-10  228.882461  229.757686  228.269795  228.863007   67615300
2017-04-11  228.435114  228.707407  226.918050  228.590714   88045300
2017-04-12  228.279515  228.493462  227.336211  227.589050   81864400
2017-04-13  227.209805  228.036418  226.110901  226.110901   92880400
2017-04-17  226.694373  228.114197  226.470707  228.114197   68405400
2017-04-18  227.287575  228.036387  226.665190  227.433441   83225800
2017-04-19  228.065567  228.483726  226.762436  227.015289   68699900
2017-04-20  227.705756  229.358981  227.345944  228.863007   92572200
2017-04-21  228.775475  228.833822  227.686305  228.133636  110389800
2017-04-24  230.652359  230.876040  228.104471  230.642639  119209900
2017-04-25  231.362295  232.373665  231.265041  231.984680   76698300
2017-04-26  231.945765  232.937696  231.790179  231.838791   84702500
2017-04-27  232.198614  232.373654  231.430349  232.033295   57410300
2017-04-28  232.325027  232.354201  231.381723  231.527603   53247400

                                          IWM                          \
           Dividends Stock Splits        Open        High         Low
Date
2017-01-03     0.000          1.0  133.525748  133.858361  131.578961
2017-01-04     0.000          1.0  133.095296  134.963819  133.056157
2017-01-05     0.000          1.0  134.504024  134.768150  132.567015
2017-01-06     0.000          1.0  133.447453  133.740941  132.733296
2017-01-09     0.000          1.0  132.596371  132.772470  131.578964
2017-01-10     0.000          1.0  132.068091  133.418126  131.833299
2017-01-11     0.000          1.0  133.271383  133.819218  132.478976
2017-01-12     0.000          1.0  133.202903  133.261597  130.688710
2017-01-13     0.000          1.0  132.703982  133.995321  132.703982
2017-01-17     0.000          1.0  132.655064  132.743105  131.216988
2017-01-18     0.000          1.0  131.833300  132.009397  131.040893
2017-01-19     0.000          1.0  132.205041  132.498529  130.277824
2017-01-20     0.000          1.0  130.845231  131.950695  130.845231
2017-01-23     0.000          1.0  131.119148  131.755026  130.228908
2017-01-24     0.000          1.0  131.422455  133.320326  131.305066
2017-01-25     0.000          1.0  134.083352  134.562715  133.975740
2017-01-26     0.000          1.0  134.357286  134.513815  133.457268
2017-01-27     0.000          1.0  133.799660  134.063785  132.703974
2017-01-30     0.000          1.0  132.293093  132.302885  130.346320
2017-01-31     0.000          1.0  130.962611  132.615911  130.581082
2017-02-01     0.000          1.0  133.261597  133.897474  131.774604
2017-02-02     0.000          1.0  132.361565  132.723525  131.569159
2017-02-03     0.000          1.0  133.036612  134.005103  132.567027
2017-02-06     0.000          1.0  133.437683  133.809435  132.488748
2017-02-07     0.000          1.0  132.870293  133.506170  131.843093
2017-02-08     0.000          1.0  132.302893  132.302893  130.982206
2017-02-09     0.000          1.0  132.068089  134.269224  132.068089
2017-02-10     0.000          1.0  134.797509  135.364915  134.220326
2017-02-13     0.000          1.0  135.756226  136.186673  135.090986
2017-02-14     0.000          1.0  134.944260  135.932321  134.621426
...              ...          ...         ...         ...         ...
2017-03-17     1.033          1.0  135.139914  135.717097  134.327939
2017-03-20     0.000          1.0  135.276874  135.511666  134.386633
2017-03-21     0.000          1.0  135.501866  135.589923  131.011554
2017-03-22     0.000          1.0  130.806103  131.393063  129.896293
2017-03-23     0.000          1.0  131.089800  132.752877  130.737617
2017-03-24     0.000          1.0  132.399311  132.909486  131.329917
2017-03-27     0.000          1.0  130.250728  132.517079  129.897531
2017-03-28     0.000          1.0  131.742026  133.331402  131.604672
2017-03-29     0.000          1.0  133.135154  133.910231  132.742721
2017-03-30     0.000          1.0  133.743458  134.783422  133.684581
2017-03-31     0.000          1.0  134.822667  135.558491  134.351743
2017-04-03     0.000          1.0  135.362257  135.489805  133.037057
2017-04-04     0.000          1.0  133.360805  133.969096  132.791780
2017-04-05     0.000          1.0  134.243794  134.832444  131.545771
2017-04-06     0.000          1.0  131.997089  133.066499  131.300517
2017-04-07     0.000          1.0  132.654450  133.458944  132.203138
2017-04-10     0.000          1.0  132.909539  134.263461  132.605401
2017-04-11     0.000          1.0  132.713303  134.332111  132.526892
2017-04-12     0.000          1.0  134.057405  134.116269  132.369913
2017-04-13     0.000          1.0  132.330675  132.811404  131.133733
2017-04-17     0.000          1.0  131.535983  132.762357  131.153340
2017-04-18     0.000          1.0  132.173664  132.899683  131.624251
2017-04-19     0.000          1.0  133.125379  134.371380  132.978205
2017-04-20     0.000          1.0  133.763087  135.067951  133.576676
2017-04-21     0.000          1.0  134.646069  134.950208  134.126088
2017-04-24     0.000          1.0  136.451292  136.706372  135.872446
2017-04-25     0.000          1.0  137.589342  138.217245  137.442168
2017-04-26     0.000          1.0  137.520672  139.139494  137.481435
2017-04-27     0.000          1.0  138.668547  139.119859  137.824801
2017-04-28     0.000          1.0  138.364438  138.501791  136.412044


                 Close    Volume Dividends Stock Splits
Date
2017-01-03  132.576813  29792400     0.000          1.0
2017-01-04  134.787720  34499400     0.000          1.0
2017-01-05  133.232254  30286900     0.000          1.0
2017-01-06  132.743088  23436000     0.000          1.0
2017-01-09  131.872452  22572800     0.000          1.0
2017-01-10  133.134415  21684900     0.000          1.0
2017-01-11  133.369217  27428800     0.000          1.0
2017-01-12  132.342010  41844200     0.000          1.0
2017-01-13  133.300735  27784500     0.000          1.0
2017-01-17  131.490906  26626800     0.000          1.0
2017-01-18  131.921356  21289700     0.000          1.0
2017-01-19  130.845230  34105900     0.000          1.0
2017-01-20  131.520248  29286100     0.000          1.0
2017-01-23  130.972412  20537000     0.000          1.0
2017-01-24  132.977921  34313800     0.000          1.0
2017-01-25  134.230103  29127300     0.000          1.0
2017-01-26  133.692062  22255600     0.000          1.0
2017-01-27  133.232254  19467800     0.000          1.0
2017-01-30  131.373505  40464400     0.000          1.0
2017-01-31  132.293076  32945000     0.000          1.0
2017-02-01  132.214828  30010500     0.000          1.0
2017-02-02  131.882202  19935700     0.000          1.0
2017-02-03  133.897491  24534100     0.000          1.0
2017-02-06  132.889847  23691500     0.000          1.0
2017-02-07  132.302887  30342200     0.000          1.0
2017-02-08  132.068100  32956900     0.000          1.0
2017-02-09  133.926819  28267600     0.000          1.0
2017-02-10  134.944260  27287600     0.000          1.0
2017-02-13  135.296432  23245100     0.000          1.0
2017-02-14  135.746445  26348100     0.000          1.0
...                ...       ...       ...          ...
2017-03-17  135.452972  33324600     0.000          1.0
2017-03-20  134.865997  19091200     0.000          1.0
2017-03-21  131.060471  61869000     0.000          1.0
2017-03-22  131.089798  46332600     0.000          1.0
2017-03-23  131.852859  37764600     0.000          1.0
2017-03-24  131.948013  33514400     0.387          1.0
2017-03-27  132.193314  35596700     0.000          1.0
2017-03-28  133.223480  26891900     0.000          1.0
2017-03-29  133.655136  22119500     0.000          1.0
2017-03-30  134.665680  25792900     0.000          1.0
2017-03-31  134.881531  29434300     0.000          1.0
2017-04-03  133.458923  38834900     0.000          1.0
2017-04-04  133.301941  25642600     0.000          1.0
2017-04-05  131.791046  44968800     0.000          1.0
2017-04-06  133.017441  41012100     0.000          1.0
2017-04-07  132.958588  24300200     0.000          1.0
2017-04-10  133.252930  22779900     0.000          1.0
2017-04-11  134.312485  32589200     0.000          1.0
2017-04-12  132.487640  25700800     0.000          1.0
2017-04-13  131.192596  30207000     0.000          1.0
2017-04-17  132.732910  18278800     0.000          1.0
2017-04-18  132.762329  24553300     0.000          1.0
2017-04-19  133.223480  34627600     0.000          1.0
2017-04-20  134.920792  31934400     0.000          1.0
2017-04-21  134.616638  29386000     0.000          1.0
2017-04-24  136.294312  33836900     0.000          1.0
2017-04-25  137.618774  32751700     0.000          1.0
2017-04-26  138.325180  41669200     0.000          1.0
2017-04-27  138.285919  23004300     0.000          1.0
2017-04-28  136.431671  28206700     0.000          1.0

[81 rows x 14 columns]